version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/KartChrono.Abstractions"
    - "src/KartChrono"
    - "src/KartChrono.Cli"
    - "src/Tests/KartChrono.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: "devcontainers"
  directory: "/"
  schedule:
    interval: weekly
